In [1]:
import os
import myServices as ms
import randForReg as rfr
import numpy as np
import pandas as pd
import sklearn
import joblib

/Users/abdielfer/DESS/Internship2022/RNCanWork/FloodProbabRNCanAbd/randForReg.py:228: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path=f"config", config_name="config.yaml")


In [2]:
# to compute ececution time do:
# with timeit():
#     # your code, e.g., 
class timeit(): 
    from datetime import datetime
    def __enter__(self):
        self.tic = self.datetime.now()
    def __exit__(self, *args, **kwargs):
        print('runtime: {}'.format(self.datetime.now() - self.tic))

## Random Forest Section

In [ ]:
sklearn.metrics.get_scorer_names()

In [2]:
DS = pd.read_csv('./basin1CleanToTrain.csv')

In [ ]:
# DS.isna().sum()
# DS.dropna(inplace = True)
DS.drop(columns=['Unnamed: 0','x_coord', 'y_coord'],inplace = True)

In [9]:
DS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2479538 entries, 0 to 2479537
Data columns (total 7 columns):
 #   Column      Dtype  
---  ------      -----  
 0   percentage  int64  
 1   disToRiv    float64
 2   TWI         float64
 3   TPI         float64
 4   FAcc        float64
 5   slope       float64
 6   elevation   float64
dtypes: float64(6), int64(1)
memory usage: 132.4 MB


In [4]:
DS['percentage'].unique()

array([0, 1, 5])

In [35]:
DS['percentage'].value_counts()

0    2426656
5      43820
1       9062
Name: percentage, dtype: int64

In [3]:
rfr.printArrayBalance(np.array(DS['percentage']))

values, counts
[[      0 2426656]
 [      1    9062]
 [      5   43820]]


In [11]:
DS.to_csv('./basin1CleanToTrain.csv')

In [10]:
# DS['weights'] = DS['percentage'].map({0:3, 1: 60, 5: 37})
sample = DS.sample(n=10000) # or use : frac=0.05
print(sample.head)
sample['percentage'].unique()

<bound method NDFrame.head of          Unnamed: 0  percentage   disToRiv       TWI      TPI         FAcc  \
1551985     1551985           0  254.01772   1.88030  0.10611     25.27690   
417661       417661           0  125.00000  12.98989  0.00656    437.96182   
1767520     1767520           0  303.64453  10.19885  0.14658     26.87236   
935600       935600           0   11.18034  18.14402 -0.73233  75831.19531   
2197356     2197356           0   58.52350  14.58681 -0.03200   2162.57227   
...             ...         ...        ...       ...      ...          ...   
957956       957956           0  226.38463   6.30505 -0.01903    185.85275   
828461       828461           0  100.00000  16.24036 -0.48613  11300.52734   
2425651     2425651           0  306.47186  14.11387  0.00378   1347.64758   
1972384     1972384           0  161.01242   4.80573 -0.12265    150.87387   
2075327     2075327           0   38.07887  10.61422 -0.29608   7425.96240   

           slope  elevation  
155

array([0, 5, 1])

In [ ]:
sample['percentage'] = sample['percentage']*10

In [11]:
print(sample['percentage'].unique())

[0 5 1]


In [ ]:
sample['percentage'].value_counts()

In [ ]:
sample.drop(columns=['x_coord', 'y_coord'],inplace = True)
print(sample.head)

In [12]:
sample.to_csv('./sample.csv')

In [2]:
#Data import and exploration
datasetPath = './sample.csv'
rfReg  = rfr.implementRandomForestRegressor(datasetPath,'percentage', 0.2)
x_train,x_validation,y_train, y_validation = rfReg.getSplitedDataset()

In [ ]:
with timeit():
    bestEstimator = rfReg.fitRFRegressorWeighted(False)

In [ ]:
# import executeRFReg as exe
with timeit():
    rfr.main()

In [3]:
estimator = joblib.load('./models/rwReg/rfwgs_2207200845.pkl')

In [4]:
print(estimator)

RandomForestRegressor(max_depth=12, max_features=0.30000000000000004,
                      n_estimators=65, random_state=50)


In [10]:
weights = rfr.createWeightVector(y_validation,0,0.1)
y_hate = estimator.predict(x_validation)
r2 = sklearn.metrics.r2_score(y_validation,y_hate,sample_weight = weights)
print(r2)

-33.022138505829034


In [21]:
y_validation =  (np.array(y_validation).astype('float')).ravel()
print(rfr.validateWithR2(estimator,x_validation,
                         y_validation, False, 0,0.3))

-200.0360085221386


In [ ]:
k = ms.importConfig()

In [6]:
print(k[0])

'./sample.csv'



In [15]:
X = [0,1,0,1,5,5,0,1,5,0]

In [16]:
X = rfr.quadraticRechapeLabes(X, -0.125, 0.825)
print(X)

[0.  0.7 0.  0.7 1.  1.  0.  0.7 1.  0. ]


In [13]:
x = [0,1,0,1,5,5,0,1,5,0]
x = np.array(x.copy())
v = (-0.125*x*x) + (0.825*x) 
print(x)
print(v)

[0 1 0 1 5 5 0 1 5 0]
[0.  0.7 0.  0.7 1.  1.  0.  0.7 1.  0. ]


In [14]:
print(x)


[0 1 0 1 5 5 0 1 5 0]


In [7]:
print(eval("np.linspace(80, 150, 20).astype(int)"))

[ 80  83  87  91  94  98 102 105 109 113 116 120 124 127 131 135 138 142
 146 150]
